# Generated by Django 3.2 on 2021-04-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='casual', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
